export const CREATURES = {
  // Positive
  joy: "butterflies",
  love: "hummingbirds",
  hope: "cicadas",
  excitement: "dragonflies",
  serenity: "doves",
  creativity: "dragonflies",
  lust: "peacock",
  resilience: "ants",
  silliness: "parrots",

  // Neutral
  curiosity: "grasshopper",
  awe: "fireflies",
  contemplative: "koi",

  // Negative
  confusion: "frogs",
  boredom: "moths",
  embarrassment: "mole",
  sadness: "raven",
  anxiety: "deathwatch beetle",
  anger: "hornets",
  guilt: "owl",
  loneliness: "worms",
  disappointment: "worms",
  jealousy: "spider",

  // Secondary
  nostalgia: "ravens",
  relief: "doves",
  calm: "koi",
  contentment: "butterflies",
  pride: "frogs",
  gratitude: "hummingbirds",
  affection: "butterflies",
  tenderness: "hummingbirds",
  longing: "cicadas",
  melancholy: "raven",
  regret: "ravens",
  frustration: "worms",
  resentment: "hornets",
  irritation: "bees",
  shame: "worms",
  uncertainty: "hedgehog",
  insecurity: "mole",
  fear: "glowing eyes",
  worry: "mole",
  stress: "worms",
  tension: "deathwatch beetle",
  restlessness: "hummingbirds",
  anticipation: "beetles",
  surprise: "parrots",
  inspiration: "dragonflies",
  motivation: "bees",
  determination: "ants",
  discouragement: "spiders",
  emptiness: "moths",
  peacefulness: "koi",
  comfort: "hedgehog",
  warmth: "salamander",
  admiration: "fireflies",
  compassion: "white parrot",
  sympathy: "robins",
  isolation: "grasshopper",
  affirmation: "doves",
  validation: "owl",
  confidence: "peacock",
};
