export const SMALL_FISH = {
  // Positive
  joy: "surge wrasse",
  love: "seahorses",
  hope: "koi carp",
  excitement: "dactylopterus volitans",
  serenity: "aurelia auritas",
  creativity: "feather stars",
  lust: "full moon bettas",
  resilience: "crabs",
  silliness: "pipefish",

  // Neutral
  curiosity: "brittle stars",
  awe: "lion’s mane jellyfish",
  contemplative: "chrysaora jellyfish",

  // Negative
  confusion: "antennarius striatus",
  boredom: "mussels",
  embarrassment: "chaunacidae",
  sadness: "bubble eye goldfish",
  anxiety: "plecos",
  anger: "sea urchins",
  guilt: "longhorn cowfish",
  loneliness: "dead fish",
  disappointment: "sea cucumber",
  jealousy: "chromis viridis",

  // Secondary
  nostalgia: "angelfish",
  relief: "gouramis",
  calm: "metynnis argenteus",
  contentment: "flower hat jellies",
  pride: "lionfish",
  gratitude: "parrotfish",
  affection: "pelagia noctiluca",
  tenderness: "butterflyfish",
  longing: "cryptotora thamicola",
  melancholy: "surgeonfish",
  regret: "stonefish",
  frustration: "boxfish",
  resentment: "actinoptilum molle",
  irritation: "puffer fish",
  shame: "turbot",
  uncertainty: "kuhli loach",
  insecurity: "clams",
  fear: "vampire squid",
  worry: "shrimps",
  stress: "electric eels",
  tension: "gannets",
  restlessness: "halitrephes maasi",
  anticipation: "clownfish",
  surprise: "garden eels",
  inspiration: "flamingos",
  motivation: "octopus",
  determination: "epaulette shark",
  discouragement: "toad",
  emptiness: "nemertea",
  peacefulness: "phycodurus eques",
  comfort: "lobsters",
  warmth: "axolotls",
  admiration: "dragonet mandarins",
  compassion: "cuttlefish",
  sympathy: "white moor goldfish",
  isolation: "nautilus",
  affirmation: "starfish",
  validation: "fairy basslets",
  confidence: "bioluminescent comb jellies"
}