export const SPACE_SPRITES = {
  // POSITIVE
  joy: "swarm of tiny luminous space-creatures and playful micro-ships zipping happily through the scene",
  love: "pair of softly glowing orbital life-forms drifting close together with gentle synchronized motion",
  hope: "small newborn energy-creatures and micro-asteroids shimmering with rising brightness",
  excitement: "burst of fast darting nano-ships and spark-sprites racing in energetic arcs",
  serenity: "slow drifting orbs, gentle alien motes, and micro-stones floating in peaceful harmony",
  creativity: "colour-shifting nebula organisms, odd drifting constructs, and curious experimental nano-craft",
  lust: "deep red swirling bio-lights and sensuous ribbon-like space fauna weaving around each other",
  resilience: "tough dwarf-stone fragments and sturdy micro-probes glowing with steady unwavering light",
  silliness: "bouncy bubble-creatures, tumbling mini-rocks, and silly wobbling micro-ships",

  // NEUTRAL
  curiosity: "wandering scout drones, probing alien motes, and drifting sensor spores scanning the dark",
  awe: "dense shimmering cloud of swirling micro-galactic organisms and tiny synchronized craft",
  contemplative: "few slow circling embers, lone drifting stones, and quiet silent motes",

  // NEGATIVE
  confusion: "erratic flickers, disordered micro-asteroids, and twitching alien sparks moving unpredictably",
  boredom: "dull drifting dust, slow half-powered drones, and muted stones with no glow",
  embarrassment: "shy pink glimmers, tiny creatures hiding behind drifting shadow-rocks",
  sadness: "fading blue motes and slow sinking debris dissolving into darkness",
  anxiety: "jittery micro-ships, trembling sparks, and twitching alien motes flashing unevenly",
  anger: "aggressive red flare-creatures, sharp-edged fragments, and spitting sparks",
  guilt: "ashen cinder-motes, dim looping probes, and dark drifting remnants",
  loneliness: "single faint drifting life-form or lone tiny ship floating in vast emptiness",
  disappointment: "weak half-lit motes, unstable drones, and dim stones that never ignite",
  jealousy: "murky greenish lights lurking at the edge of brighter clusters, watching silently",

  // SECONDARY EMOTIONS
  nostalgia: "soft old-tech probes and golden flicker-creatures echoing like fading memories",
  relief: "small sparks and micro-ships settling gently back into steady patterns",
  calm: "simple slow orbits of quiet motes and drifting stones",
  contentment: "cluster of warm glowing creatures grouped in peaceful harmony",
  pride: "solitary bright mote or tiny craft shining confidently above the others",
  gratitude: "cluster of supportive glimmers leaning toward a calmer central glow",
  affection: "two gentle motes or micro-creatures moving together in a shared halo",
  tenderness: "soft pink nebula creatures sheltering smaller drifting lights",
  longing: "dim spark or micro-ship extending a faint trail toward a distant glow",
  melancholy: "blue-tinted drifting organisms wandering slowly through the void",
  regret: "brief flares of life or light dying back quickly into darkness",
  frustration: "sparks or tiny ships bursting then failing to stabilize",
  resentment: "low green glows and dark fragments lingering at the edge of a bright field",
  irritation: "sharp micro-flashes snapping in uneven bursts",
  shame: "dim drifting creatures retreating behind dust veils",
  uncertainty: "wandering lights shifting direction without pattern",
  insecurity: "small motes clinging closely to larger overshadowing entities",
  fear: "trembling bio-light shrinking away from a looming shadow form",
  worry: "cluster of dim sparks hovering near a dark cosmic rift",
  stress: "tight vibrating cluster of jittery particles and micro-craft",
  tension: "thin taut sequence of motes pulled between unseen forces",
  restlessness: "small sparks or creatures pacing in anxious loops",
  anticipation: "gathering motes circling near a brightening region",
  surprise: "sudden bright pop of a tiny new creature or drone appearing",
  inspiration: "small comet-like sprites sketching arcs of light",
  motivation: "focused stream of tiny ships or lights moving with purpose",
  determination: "single intense spark holding steady against surrounding darkness",
  discouragement: "weakening glow shrinking into a faint ember",
  emptiness: "barely-there dust of drifting light in a vast silent void",
  peacefulness: "soft motes breathing in slow harmonious rhythms",
  comfort: "cluster of warm glimmers huddled like a small luminous family",
  warmth: "gentle orange halo wrapping tiny drifting lights",
  admiration: "ring of small orbiting motes turning calmly around a central radiant point",
  compassion: "cool blue motes leaning protectively around a fading ember",
  sympathy: "pair of dim glows drifting together in shared motion",
  isolation: "single spark drifting far from any constellation or cluster",
  affirmation: "motes lighting up gently in response to a bright central glow",
  validation: "dim mote brightening as surrounding lights turn toward it",
  confidence: "small bright entity shining far stronger than its size suggests",
};
